import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { supabase } from './supabaseClient';
import StructuredHealthCard from './StructuredHealthCard';

function SharedView() {
  const { patientId } = useParams();
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchPatientData = async () => {
      // Fetch the verified records for this specific patient
      const { data } = await supabase
        .from('medical_records')
        .select('*')
        .eq('patient_id', patientId)
        .order('uploaded_at', { ascending: false });

      if (data) setRecords(data);
      setLoading(false);
    };

    fetchPatientData();
  }, [patientId]);

  if (loading) return <div style={{ padding: '40px', textAlign: 'center' }}>Loading patient timeline...</div>;

  return (
    <div style={{ padding: '20px', maxWidth: '600px', margin: '0 auto', fontFamily: 'sans-serif' }}>
      
      {/* Trust Header */}
      <div style={{ backgroundColor: '#e6f0ff', padding: '20px', borderRadius: '12px', marginBottom: '25px', border: '1px solid #cce0ff' }}>
        <h2 style={{ color: '#0066ff', margin: 0 }}>MedBridge Health Timeline</h2>
        <p style={{ margin: '8px 0 0 0', fontSize: '14px', color: '#555' }}>
          <span style={{ backgroundColor: '#e8f5e9', color: '#2e7d32', padding: '4px 8px', borderRadius: '4px', fontWeight: 'bold', fontSize: '12px' }}>
            ✅ Verified Patient Data
          </span>
        </p>
      </div>
      
      {/* The Medical Timeline */}
      <h3 style={{ borderBottom: '2px solid #f0f0f0', paddingBottom: '10px', marginBottom: '20px' }}>Clinical Records</h3>
      
      {records.length === 0 ? (
        <p style={{ color: '#888' }}>No records have been shared by this patient.</p>
      ) : (
        records.map((record) => (
          <div key={record.id} style={{ marginBottom: '20px', padding: '20px', border: '1px solid #e0e0e0', borderRadius: '12px', backgroundColor: '#fafafa' }}>
            
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' }}>
              <h4 style={{ margin: 0, fontSize: '16px' }}>{record.document_type}</h4>
              <a href={record.file_url} target="_blank" rel="noopener noreferrer" style={{ color: '#0066ff', fontSize: '14px', fontWeight: 'bold', textDecoration: 'none' }}>
                View Original Document ↗
              </a>
            </div>

            {/* Structured Text Box */}
            <div style={{ backgroundColor: 'white', padding: '15px', borderRadius: '8px', border: '1px solid #eee' }}>
              <StructuredHealthCard textData={record.extracted_text} />
            </div>
            
          </div>
        ))
      )}

      {/* Legal Shield Footer */}
      <div style={{ marginTop: '40px', padding: '15px', backgroundColor: '#fff3e0', borderRadius: '8px', borderLeft: '4px solid #ff9800' }}>
        <p style={{ fontSize: '12px', color: '#666', margin: 0, lineHeight: '1.5' }}>
          <strong>Legal Disclaimer:</strong> This page is a patient-managed health record summary generated by MedBridge AI. It does not constitute an official medical diagnosis or clinical advice. All extracted text has been self-verified by the patient. Always verify critical information directly with the original attached documents.
        </p>
      </div>

    </div>
  );
}

export default SharedView;